### ISSUE TITLE
Building prerequisites not working (YAML)

### ISSUE THREAD

**Issue by trolando** [jkeiren/paritygame-generator#1]
When installing prerequisites, yaml download not found...

but 

apt install libyaml-cpp-dev works
(and removing the two defines for YAML locations in the cmake call in install_prerequisites.sh)

**Comment by jkeiren** [comment]
I simply fixed the download location, for two reasons:
1. I would like to preserve the original setup as much as possible.
2. I have been running a lot of these experiments on systems on which I do not have admin rights, so a non-admin solution for installing YAML is preferred.

Feel free to submit a patch that uses a newer version of YAML, though.
